### ISSUE TITLE
Duplicate methods are allowed

### ISSUE THREAD

**Issue by ikarienator** [zenparsing/esparse#37]
https://github.com/zenparsing/esparse/blob/b86c20ee87167493b0cb60e2e75d9ce9fdc3fb2b/test/parse/classes/class.js#L167

According to https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions-static-semantics-early-errors only duplicate constructors are not allowed.

**Comment by zenparsing** [comment]
hi @ikarienator !

Yes - that's what the test is verifying - multiple occurrences of the same name are fine, as long as it's not "constructor" (there's another test for that later on down).

**Comment by ikarienator** [comment]
Ah. I miss read it... Nice...
