### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by codesdk** [zenparsing/esparse#40]
npm install causing the following error 
npm WARN package.json LX-Launcher@1.0.0 No repository field.
npm WARN package.json LX-Launcher@1.0.0 license should be a valid SPDX license expression
npm ERR! Linux 3.16.0-40-generic
npm ERR! argv "_xxx_/.nvm/versions/v0.12.5/bin/node" "_xxx_/.nvm/versions/v0.12.5/bin/npm" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path xxx/node_modules/famous/node_modules/glslify/node_modules/replace-method/node_modules/recast/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '_xxx_/node_modules/famous/node_modules/glslify/node_modules/replace-method/node_modules/recast/node_modules/esprima/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!    _xxx_/npm-debug.log

**Comment by zenparsing** [comment]
Thanks - honestly I haven't bothered updating the version on npm for a long time.  I'll check it out tonight though.

**Comment by zenparsing** [comment]
Looks like an error while trying to install esprima as a dependency of something else?  I don't think this has anything to do with this project.
